version: '3.8'
services:
  aria2-ariang:
    container_name: aria2-ariang
    restart: unless-stopped
    ports:
      - "8089:8089"       # Web 访问端口
      - "6803:6800"     # RPC 端口
      # 如果需要 BT/DHT 功能，取消下面两行注释
      - "6881:6881"    # BT 端口 (TCP)
      - "6881:6881/udp" # DHT 端口 (UDP)
    
    environment:
      - PUID=
      - PGID=
      - TZ=Asia/Shanghai
    volumes:
      - ./downloads:/root/downloads   # 下载目录
      # - ./aria2.session:/etc/aria2.session  # 会话文件
      # 可选：挂载配置文件用于热更新（需要时取消注释）
      # - ./aria2.conf:/etc/aria2.conf
      # - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
