version: "3.8"

services:

  Aria2-Pro:
    container_name: aria2
    image: ghcr.nju.edu.cn/
    environment:
      - PUID=
      - PGID=
      - DISK_CACHE=64M
      - TZ=Asia/Shanghai
    volumes:
      - ${PWD}/aria2-config:/config
      - ${PWD}/aria2-downloads:/downloads
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
    network_mode: host
#    network_mode: bridge
#    ports:
#      - 6800:6800
#      - 6888:6888
#      - 6888:6888/udp
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: 
    command: --port 6880
    network_mode: host
#    network_mode: bridge
#    ports:
#      - 16800:16800
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
