name: Docker to ghcr

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      image_name:
        description: '镜像名称 (如: my-app)'
        required: true
        default: 'my-app'
      image_tag:
        description: '镜像标签 (如: v1.0)'
        required: true
        default: 'latest'
      target_arch:
        description: '目标架构'
        required: true
        type: choice
        options:
          - amd64
          - arm64
        default: 'amd64'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ${{ contains(inputs.target_arch, 'arm') && 'ubuntu-latest' || 'ubuntu-latest' }}
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU (仅ARM需要)
      if: ${{ inputs.target_arch == 'arm64' }}
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 构建并推送 ${{ inputs.target_arch }} 架构镜像
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/${{ inputs.target_arch }}
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
        build-args: |
          TARGETARCH=${{ inputs.target_arch }}
        
    - name: 显示镜像信息
      run: |
        echo "成功构建镜像:"
        echo "${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ inputs.image_tag }}"
        echo "架构: ${{ inputs.target_arch }}"
