name: Build and Push Multi-arch Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

env:
  # 自定义镜像名称 (去掉特殊字符)
  IMAGE_NAME: my-app
  # 支持的CPU架构
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # 用于自动令牌认证

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 自动登录到 GHCR (无需显式PAT)
      - name: Auto Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # 使用自动生成的令牌

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      # 构建并推送多架构镜像
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # 指定Dockerfile路径
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 生成镜像报告
      - name: Show image digest
        run: echo "Image pushed to ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}"
