name: Docker to ghcr

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker Image Name'
        required: true
        default: 'my-app'
      image_tag:
        description: 'Docker Image Tag'
        required: true
        default: 'latest'
      target_platforms:
        description: 'Target Platforms (comma separated)'
        required: true
        default: 'linux/amd64'

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository_owner }}/${{ inputs.image_name || 'my-app' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse target platforms
        id: platform
        run: |
          PLATFORMS=$(echo '${{ inputs.target_platforms || 'linux/amd64,linux/arm64' }}' | tr ',' '\n' | awk '{ printf "--platform=" $1 " " }')
          echo "PLATFORMS_STR=$PLATFORMS" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ inputs.image_tag || github.sha }}
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
          outputs: type=registry
          platforms: ${{ inputs.target_platforms || 'linux/amd64,linux/arm64' }}
